### ISSUE TITLE
APKs will be overritten with same name after build

### ISSUE THREAD

**Issue by birmacher** [bitrise-io/steps-gradle-runner#12]
If you generate APKs with the same name, the step will override them when it moves them to BITRISE_DEPLOY_DIR

```
🚀  Copy ./app/build/outputs/apk/app-release.apk to /bitrise/deploy/app-release.apk
🚀  Copy ./app/app-release.apk to /bitrise/deploy/app-release.apk

Exporting output: $BITRISE_APK_PATH => /bitrise/deploy/app-release.apk
```

**Comment by godrei** [comment]
Hi @birmacher ,
thanks for the report, the issue is solved in [1.5.0](https://github.com/bitrise-io/steps-gradle-runner/releases/tag/1.5.0)
