### ISSUE TITLE
Arguments are not correctly escaped

### ISSUE THREAD

**Issue by scruffyfox** [bitrise-io/steps-gradle-runner#13]
Setting input values with quotes get double quoted when executed.

Input values:
```
 --stacktrace -PappIcon=\"can_launcher\" -PappId="GDPC-4-3" -PappName="Be Ready" -PgaId="UA-abc-1" -PgcmId=1234 -PkeyAlias="gdpc - fa - can" -PkeyPassword=abc -Psociety=can
```

outputs fine from the gradle configuration debug, but when gets executed results in

```
+ ./gradlew --build-file Codebase/build.gradle assembleRelease --stacktrace '-PappIcon=\"can_launcher\"' '-PappId="GDPC-4-3"' '-PappName="Be' 'Ready"' '-PgaId="UA-abc-1"' -PgcmId=1234 '-PkeyAlias="gdpc' - fa - 'can"' -PkeyPassword=abc -Psociety=can
```

I've tried with single quotes, with double quotes, with escaped quotes, and all produce no solution

**Comment by godrei** [comment]
Hi @scruffyfox ,
thanks for the report, the issue is solved in [1.5.0](https://github.com/bitrise-io/steps-gradle-runner/releases/tag/1.5.0).
