### ISSUE TITLE
Can no longer specify multiple Gradle tasks to run

### ISSUE THREAD

**Issue by julo15** [bitrise-io/steps-gradle-runner#15]
Prior to v1.5, it was possible to specify multiple tasks to run in the `gradle_task` parameter, e.g. setting `gradle_task` to `assemble publishToMavenLocal`. This would produce the following command:
```
/bitrise/src/gradlew --build-file /bitrise/src/build.gradle assemble publishToMavenLocal --stacktrace
```

With the update to v1.5, the parameters get wrapped in quotes:
```
/bitrise/src/gradlew "--build-file" "/bitrise/src/build.gradle" "assemble publishToMavenLocal" "--stacktrace"
```

... which now produces the following error because of the quotes:
```
* Exception is:
org.gradle.execution.TaskSelectionException: Task 'assemble publishToMavenLocal' not found in root project 'sdk'.
```

This may be related to the change to address [this](https://github.com/bitrise-io/steps-gradle-runner/issues/13) issue.

Is this new behaviour expected?

**Comment by viktorbenei** [comment]
Ouch, you're right, this is a new issue with the latest step - we'll fix it ASAP and push a new version. In the meantime please downgrade to the previous version of the step, we'll let you know as soon as the fix is published!

**Comment by julo15** [comment]
@viktorbenei will do. thanks for the quick response!

**Comment by viktorbenei** [comment]
Thanks for reporting the issue! ;)

**Comment by godrei** [comment]
@julo15 ,
thanks for the report, new version [v 1.5.1](https://github.com/bitrise-io/steps-gradle-runner/releases/tag/1.5.1) with the fix is available in the steplib.

**Comment by julo15** [comment]
just tried it out and it works :)

for reference (to anyone curious), new in v1.5.1 vs. v1.4.1 is each parameter is wrapped in quotes:
```
/bitrise/src/gradlew "--build-file" "/bitrise/src/build.gradle" "assemble" "publishToMavenLocal" "--stacktrace"
```

thanks so much for the fast response.

**Comment by viktorbenei** [comment]
You're right @julo15 and thanks for the info for others!

The change was actually that the step was rewritten from Bash to Go, using the new Bitrise CLI v1.4.0 built in Go Toolkit ( http://blog.bitrise.io/2016/09/13/monthly-release-of-bitrise-cli-sept.html ). It was rewritten mainly to have precise control over what/which input gets escaped and what not, as that's way harder to control in Bash
