### ISSUE TITLE
v1.5.1: Specifying empty `mapping_file_include_filter` causes insane copy to bitrise deploy directory

### ISSUE THREAD

**Issue by julo15** [bitrise-io/steps-gradle-runner#17]
Specifying an empty string for `mapping_file_include_filter`, i.e.
```
inputs:
- mapping_file_include_filter: ''
```
... will cause the step to try to copy every file from the source directory into the deploy directory :(.

Output:
```
Move mapping files...
  find "."
  1 attempt failed:
  file already exists at: /bitrise/deploy
  Retrying...
  copy . to /bitrise/deploy/20160916220910.
skipping directory .
  copy ./android-client to /bitrise/deploy/android-client

// this goes on for a while...
```

This can be worked around by not adding the empty input, but yeah.. this probably isn't good.

**Comment by viktorbenei** [comment]
I agree, we'll fix it ASAP!

@godrei pls schedule the fix ;)

**Comment by viktorbenei** [comment]
@julo15 how would you treat the empty input? What should that mean?

If you specify an empty filter, IMO that means to copy everything. If you remove the input completely that means to use the default value, which is `*/mapping.txt` right now ( https://github.com/bitrise-io/steps-gradle-runner/blob/master/step.yml#L88 )

**Comment by viktorbenei** [comment]
This is pretty much the intended way of how the CLI works, if you specify an input with an empty value that means that you want to use an empty value; if you don't specify the input at all that means to use the step's default value for that option (if any)

**Comment by viktorbenei** [comment]
That said, an empty __include__ filter should mean.. I'm not sure whether it should mean to "include everything" or "include nothing".. Unfortunately that's not clear in this context I think

**Comment by julo15** [comment]
I don't feel strongly one way or another, but one thing worth considering is there was a change in behaviour from v1.4.1, where the empty include filter meant include nothing, and now it means include everything. (We noticed this change when switching to v1.5+.)

**Comment by viktorbenei** [comment]
@godrei WDYT? Should we treat empty include as "don't include anything"?

**Comment by godrei** [comment]
i think the step should work as previously even of the exact meaning of include filter...

in the previous version following line was collecting the mapping files:

`find_mappings_output="$(find . -path "${mapping_file_include_filter}" ! -path "${mapping_file_exclude_filter}")"`

with _empty_ include and exclude filter:

`find_mappings_output="$(find . -path "" ! -path "")"`

_it does not generate output_

So i will manage to share a new version today, which will work as previously (regarding to the filters).

@viktorbenei are you ok with that?

**Comment by viktorbenei** [comment]
I agree @godrei - go ahead and create & share a new version, thanks! :)

**Comment by godrei** [comment]
@julo15 new version [1.5.2](https://github.com/bitrise-io/steps-gradle-runner/releases/tag/1.5.2) is available in the steplib, thanks for the report!
