### ISSUE TITLE
Could not resolve all dependencies for configuration

### ISSUE THREAD

**Issue by huytq209** [bitrise-io/steps-gradle-runner#21]
```
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':printer'.
      > You have not accepted the license agreements of the following SDK components:
        [Android SDK Build-Tools 25.0.1].
        Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
        Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

In workflow, i used below 4 commands in script but still error

android update sdk --no-ui --all --filter build-tools-25.0.2
android update sdk --no-ui --all --filter extra-android-m2repository
android update sdk --no-ui --all --filter extra-google-m2repository
./gradlew dependencies

**Comment by viktorbenei** [comment]
> android update sdk --no-ui --all --filter build-tools-25.0.2

It seems your app uses `25.0.1`, not `25.0.2`, but you install `25.0.2`

Also, related changelog & solutions: https://discuss.bitrise.io/t/weekly-virtual-machine-stack-updates-2017-01-14/139
