### ISSUE TITLE
Option to disable build cache

### ISSUE THREAD

**Issue by radimvaculik** [bitrise-io/steps-gradle-runner#37]
Currently, there is no option, how to remove "build" and ".gradle" folders from cache. We always want clean build with cached gradle dependencies.

https://github.com/bitrise-io/steps-gradle-runner/blob/master/main.go#L255

**Comment by trapacska** [comment]
> This cache mechanism is developed to reach near-local-pc environment, this all happens if you build locally. On you local machine, if you want a clean build, either you run Android Studio's `Build > Clean` option, or you can put a `clean` task before your actual gradle task.

So for example `./gradlew clean assembleDebug`

I am closing this issue now, as it can be handled by default gradle behavior, but please feel free to reopen if you encounter any issue with it anytime. 🚀

Thanks again for the feedback!
