### ISSUE TITLE
gradle-runner@1.2.0 (exit code: 1)  

### ISSUE THREAD

**Issue by oldcwj** [bitrise-io/steps-gradle-runner#4]
=> Switching to specified workdir
$ cd /bitrise/src
=== CONFIGURATION ===
 * Using gradle tool: ./gradlew assemble
 * Gradle build file: ../build.gradle
 * Gradle task: app:assemble
 * Gradle options: --stacktrace
=> Running gradle task ...
+ ./gradlew assemble --build-file ../build.gradle app:assemble --stacktrace
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
|                                                                              |
+----+--------------------------------------------------------------+----------+
| 🚫  | gradle-runner@1.2.0 (exit code: 1)                           | 2.9 sec  |
+----+--------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-io/steps-gradle-runner/issues      |
| Source: https://github.com/bitrise-io/steps-gradle-runner                    |
+----+--------------------------------------------------------------+----------+

**Comment by viktorbenei** [comment]
This seems to be an issue with your `gradlew` wrapper configuration - can you try it on your own PC/Mac? : `./gradlew assemble --build-file ../build.gradle app:assemble --stacktrace`

Seems strange that your `gradlew` file is not in the same directory as your `build.gradle` file, usually both are in the same directory, but can be something else.

**Comment by oldcwj** [comment]
Thanks!

**Comment by viktorbenei** [comment]
What was the solution/issue?

**Comment by DeTakaki** [comment]
Hello, i'm having the same issue. I ran the ./gradlew command im my mac and it went fine. But when bitrise builds the project, this happens.

**Comment by DeTakaki** [comment]
Got it fixed as well. The gradle-wrapper.jar wasn't in the repository, so this error would trigger. By running "gradle wrapper" in my mac and uploading the jar to the repository i solved the issue. Thanks

**Comment by viktorbenei** [comment]
Thanks for reporting the solution @DeTakaki !
