### ISSUE TITLE
Generate dependencies map... has broken my job

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-io/steps-gradle-runner#44]
I've enabled the bitrise support user: https://www.bitrise.io/build/b41cf412d186ede8 

> Plugin with id 'kotlin-android' not found.
> Plugin with id 'kotlin-android' not found.
> Cannot get property 'compileSdkVersion' on extra properties extension as it does not exist
> Cannot get property 'compileSdkVersion' on extra properties extension as it does not exist
> Plugin with id 'com.android.application' not found.
> Plugin with id 'com.android.application' not found.
> Plugin with id 'kotlin-android' not found.

We are using `Configure project-wide properties` as [recommended by Google](https://developer.android.com/studio/build/gradle-tips.html). The pattern of `rootProject.ext.compileSdkVersion` means these gradle files can't be evaluated independently (as rootProject would contain no extra properties).

Walking the filesystem and invoking `(configs.GradlewPath, "-b", path, "dependencies", "-q")` for each build.gradle file is not safe.

**Comment by trapacska** [comment]
Hey @bootstraponline !

Exactly, thank you for reporting the issue!

It will be fixed soon!🚀

**Comment by bootstraponline** [comment]
Nice. I like the fix. 😄

**Comment by bootstraponline** [comment]
I confirmed this works now on our app. Thanks!
