### ISSUE TITLE
What is the best way to not export anything?

### ISSUE THREAD

**Issue by tir38** [bitrise-io/steps-gradle-runner#54]
I'm using this step several times in a work flow. The first time I use it I want to export generated .apks. All other times I do not want to export generated .apks nor risk overwriting any previously exported apks. What is the best way to do this? I assume that I can hack something together by using some unrealistic filter in the later steps:

<img width="415" alt="screen shot 2018-02-28 at 5 49 29 pm" src="https://user-images.githubusercontent.com/1980553/36817733-4c447548-1cb0-11e8-8c37-c5c5dbf8e2e9.png">

**Comment by viktorbenei** [comment]
Well, if you don't want to export anything the you can just run `./gradlew TASK` from e.g. a Script step.

Of course an APK filter like the one you included should also work, but ultimately this step is designed to collect certain outputs (APKs, mapping file, ...) and we might even extend the list in the future.

P.S.: if you specify an empty APK include filter that should also be enough, or maybe just `-`

If you'd have any questions just let us know! :)

**Comment by viktorbenei** [comment]
Ohh, one more thing: you can run multiple Gradle tasks with a single Gradle Runner step! That might also help, as that way the APKs will be collected & exported only once.

Multiple gradle tasks: simply specify all the ones you want to run, separated with space. E.g. `assembleDebug assembleRelease`.

**Comment by tir38** [comment]
I like the Script step idea. That would be the cleaner solution.

**Comment by viktorbenei** [comment]
Glad to hear! ;)
