### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by fchristysen** [bitrise-io/steps-gradle-runner#55]
Hi, this may not really a bug, but rather a feature request 
I'm using this gradle step inside my workflow for build and deploy my apk to crashlytics(./gradlew crashlyticsUploadDistributionRelease), but since this step automatically copy the generated apk and mapping file to bitrise artifact directory, the artifact is double on my case. 
Could you help me to create a flag to enable/disable copy to artifact dir?

**Comment by viktorbenei** [comment]
Hey @fchristysen ,

Thanks for asking! ;)

If you don't want to export any apks, simply change the "APK File include filter" input to something which will not match anything: https://github.com/bitrise-io/steps-gradle-runner/blob/645e70272d65ccd0cecff2f460d418e327f2fe23/step.yml#L63

E.g. `-` should work ;)

If you'd have any questions just let us know!
Happy Building! :)
